# Generated by Django 6.0.3 on 2026-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fuel_level', models.IntegerField(default=100)),
                ('mileage', models.IntegerField(default=0)),
                ('price_per_minute', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('rented', 'Арендована'), ('maintenance', 'На обслуживании')], default='available', max_length=20)),
                ('city', models.CharField(default='Москва', max_length=100)),
            ],
        ),
    ]
