# Generated by Django 6.0.3 on 2026-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mileage',
            new_name='odometer_reading',
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('booked', 'Забронирована'), ('checking', 'На проверке'), ('rented', 'Арендована'), ('maintenance', 'На обслуживании')], default='available', max_length=20),
        ),
    ]
