# Generated by Django 6.0.3 on 2026-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_mileage_car_odometer_reading_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
