# Generated by Django 6.0.3 on 2026-05-02 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_status_car_active_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('booked', 'Забронирована'), ('inspecting', 'На осмотре пользователем'), ('active', 'Аренда активна'), ('completed', 'Аренда завершена'), ('canceled', 'Аренда отменена')], default='booked', max_length=20),
        ),
    ]
