# Generated by Django 6.0.3 on 2026-06-26 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_rental_booked_at_alter_rental_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'booked'), _negated=True), ('booked_at__isnull', False), _connector='OR'), name='rental_booked_has_booked_at'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'inspecting'), _negated=True), ('inspection_started_at__isnull', False), _connector='OR'), name='rental_inspecting_has_inspection_started_at'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('start_time__isnull', False), _connector='OR'), name='rental_active_has_start_time'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('end_time__isnull', False), _connector='OR'), name='rental_completed_has_end_time'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('booked_at__isnull', True), ('inspection_started_at__isnull', True), ('booked_at__lt', models.F('inspection_started_at')), _connector='OR'), name='inspection_started_at_later_than_booked_at'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('inspection_started_at__isnull', True), ('start_time__isnull', True), ('inspection_started_at__lt', models.F('start_time')), _connector='OR'), name='start_time_later_than_inspection_started_at'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('start_time__lt', models.F('end_time')), _connector='OR'), name='end_time_later_than_start_time'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'inspecting', 'active'])), fields=('car',), name='one_active_rental_per_car'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('total_cost__isnull', False), _connector='OR'), name='total_cost_only_when_completed'),
        ),
    ]
