# Generated by Django 6.0.3 on 2026-06-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rental_rental_booked_has_booked_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rental',
            name='total_cost_only_when_completed',
        ),
    ]
