# Generated by Django 6.0.3 on 2026-06-28 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_rental_total_cost_only_when_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('booked_at__isnull', True), ('start_time__isnull', True), ('booked_at__lt', models.F('start_time')), _connector='OR'), name='start_time_later_than_booked_at'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('booked_at__isnull', True), ('end_time__isnull', True), ('booked_at__lt', models.F('end_time')), _connector='OR'), name='end_time_later_than_booked_at'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('inspection_started_at__isnull', True), ('end_time__isnull', True), ('inspection_started_at__lt', models.F('end_time')), _connector='OR'), name='end_time_later_than_inspection_started_at'),
        ),
    ]
